TSV-918 - GA events
hmrc/personal-details-validation pull request #9
Opened 2018-02-05 15:31 UTC by anshulbajpai

2018-02-05 16:26 UTC, burakbala commented
I think the general strategy is to ignore the error when sending a GA event fails. With the current implementation it makes the personal details validation to fail.

2018-02-05 16:26 UTC, burakbala requested changes
See the comment above

2018-02-06 10:59 UTC, anshulbajpai commented on app/uk/gov/hmrc/audit/PlatformAnalyticsConnector.scala
> +    httpClient.POST[JsObject, HttpResponse](
Add error logging for non 200 response

2018-02-06 12:18 UTC, burakbala approved these changes

2018-02-06 12:19 UTC, merged